#!/bin/sh
set -E -e -u # let shell functions inherit ERR trap, fail on any error and treat unset variables as errors

# Trap non-normal exit signals:
# 1/HUP, 2/INT, 3/QUIT, 15/TERM, ERR
trap err_handler 1 2 3 15 ERR
function err_handler {
local exit_status=${1:-$?}
logger -s -p "syslog.err" -t "ts3server.deb" "ts3server.deb script '$0' error code $exit_status (line $BASH_LINENO: '$BASH_COMMAND')"
exit $exit_status
}
# Arrange for a daemon to be started at system boot time
update-rc.d ts3server defaults >/dev/null
exit 0